name: hello_world
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  bitsdojo_window: ^0.1.1+1
  desktop_window: ^0.4.0
  flutter: 
    sdk: flutter

  flutter_dotenv: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  font_awesome_flutter: ^9.1.0
  get:
    git:
      url: git://github.com/jonataslaw/getx.git
      ref: master
  pedantic: ^1.11.0
  retry: ^3.1.0
  url_strategy: ^0.2.0


dev_dependencies: 
  flutter_native_splash: ^1.2.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets: 
    - assets/
    - .env
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
